# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Room Service • Rafael Becker
email: podcast@rafaelbecker.com
description: &desc >- # this means to ignore newlines until "baseurl:"
  Need to take a break with good music, colourful vibes and sensual beats?
  Rafael Becker shares his live sessions around the world to provide you with
  an exceptional listening experience through his musical Room Service.
baseurl: "" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: DjRafaelBecker
github_username:  rbmusic

# Build settings
theme: minima
plugins:
  - jekyll-feed

podcast:
  title: Room Service
  description: *desc
  url: /room-service.xml # podcast xml url
  author: Rafael Becker
  email: podcast@rafaelbecker.com
  album_art: /assets/images/room-service-album-art.jpg # logo in 1400 – 3000 pixel
  language: fr # http://www.loc.gov/standards/iso639-2/php/code_list.php
  category: Music # https://help.apple.com/itc/podcasts_connect/#/itc9267a2f12
  subcategory: [subcategory]
  type: episodic # episodic | serial
  explicit: false # true | false
  complete: no # 'yes' | 'no'
  block: no # 'yes' | 'no'